### PR TITLE
Refactor

### PR DESCRIPTION
**Pull request by garbados**
This PR:
- Closes https://github.com/neighbourhoodie/Tangerine_pm/issues/37
- Closes https://github.com/neighbourhoodie/Tangerine_pm/issues/33
- Closes https://github.com/neighbourhoodie/Tangerine_pm/issues/32

It refactors `index.js` to expose only two methods: `.install` and `.uninstall`.
The test suite and new readme have been incorporated and updated as well.
Additionally, this PR includes a GitHub Actions CI workflow.

### CODE REVIEW

**Review by AlbaHerrerias — APPROVED** [review]
This is a great refactor, great job! ❤️ 

Note that @hulkoba is on vacation until the beginning of August so most likely she won't be able to review this until then.

**Comment by jcoglan** [comment]
I've just got up to speed but this really good. Given what you've said elsewhere I agree with the decision to remove all the method-specific argument handling and make wrappers use the same function signatures as the public PouchDB API. It massively reduces the complexity and coupling of this module to PouchDB, and means plugin authors can work with the documented API.

It also fixes a strange behaviour with how arguments are passed from wrapper functions to the original API functions. Take this code on `master` as an example:

```js
wrapperBuilders.post = function (db, post, handlers) {
  return function (doc, options, callback) {
    var args = parseBaseArgs(db, this, options, callback);
    args.doc = doc;
    return callHandlers(handlers, args, function () {
      return post.call(this, args.doc, args.options);
    });
  };
};
```

The actual function that a wrapper will invoke by calling `original()` is this one:

```js
    function () {
      return post.call(this, args.doc, args.options);
    }
```

This doesn't have any formal arguments -- it refers to `args` from the enclosing scope. That means that if a wrapper wants to modify the inputs to the original function, it must _mutate_ the `args` object it's given, rather than passing a new/different object down the stack. This behaviour differs based on whether the next thing in the stack is the original wrapped function, or another wrapper.

The behaviour on this branch completely removes this strangeness and works by normal argument-passing between functions.

I noticed that this branch reverses the order in which `handlers` are invoked. On `master` [we apply the first installed handler first](https://github.com/neighbourhoodie/pouchdb-wrappers/blob/d4833096f74c750a0a95ccb124a35cebda7d5dc4/index.js#L462-L465) whereas in this branch we apply it last. Is this a deliberate choice and could it lead to changing application behaviour? Do any plugins rely on layering order at all?

As I mentioned elsewhere the only thing I'd like added to this is preservation of callback behaviour, which I've done on `nh-refactor-callbacks`.

Nice to see this getting much simpler and smaller :)

**Review by Realtin — COMMENTED** [review]
This is sooo good! 
Very clear and simple.  ✨ 😍 

The only open question is the one from @jcoglan about the different order in which handlers are installed.

**Comment by garbados** [comment]
Hey @jcoglan thanks for your latest commits. I've pushed a couple changes:

- Wrapped methods should not default to being async as PouchDB has a couple of synchronous methods like `.changes()`. I've added a new test to verify this behavior.
- Removed `promise-nodify` dependency.

**Comment by garbados** [comment]
I just remembered why I made the order of running wrapped methods last-first: so that the original method is run very last. Otherwise, the order is like this:

- First-added
- Original
- Subsequent handlers

This means that the first handler on `.put()` would run BEFORE the database operation, while subsequent handlers run AFTER. I want the original method to happen very last so that all handlers occur BEFORE database operations.

EDIT: Nevermind. It is very difficult to reason about code sometimes. I have a patch locally that I'm working on which implements this ordering:

- First-added
- ...
- Last-added
- Original

**Comment by jcoglan** [comment]
I believe we're happy with the state of `nh-refactor` so I have merged it into `master` and pushed the result to https://github.com/pouchdb-community/pouchdb-wrappers. I will be publishing a release of v5.0.0 shortly.

**Pull request merged**
